### ISSUE TITLE
2018-11-01 - Grundlagen F#/Funktionale Pattern

### ISSUE THREAD

**Issue by Bongolus** [softwerkskammer-hl/softwerkskammer-hl#10]

**Comment by danbim** [comment]
Super interessiert! ;-) Fände ich großartig mal was drüber zu hören und aus meiner JVM-Ecke mal ein Blick über den Tellerrand zu werfen.

**Comment by danbim** [comment]
@Bongolus wäre der Vortrag im November möglich für dich?

**Comment by Bongolus** [comment]
@danbim Gleich am 1.11.? Klar, trage ich mir ein

**Comment by danbim** [comment]
👍

**Comment by danbim** [comment]
@Bongolus Könntest Du einen kleinen einleitenden Text schreiben worum es bei dem Meetup gehen soll? Hat allerdings noch keine Eile...

**Comment by janraasch** [comment]
Finde ich 'n geiles Thema 👍. Freue mich drauf.

**Comment by Bongolus** [comment]
@danbim Moin! Wollte nur mal was von mir hören lassen. Ich bin die Woche leider noch krankgeschrieben, habe aber auch schon was organisiert, z.B. hat sich mein Chef bereit erklärt uns einen Raum zu sponsern (Breite Straße 6-8).
Der Vortrag steht auch schon größtenteils und den Text bekommst du nächste Woche.
Soviel in Kürze, LG Ralph

**Comment by danbim** [comment]
Hey, moin Ralph! Vielen Dank, das sind ja gute Nachrichten :). Wie viele Leute werden denn in den Raum passen? Gruß Daniel

**Comment by danbim** [comment]
Noch eine Frage Ralph: in unserer neuen Meetup-Gruppe (https://www.meetup.com/agile-lean-hl/) haben wir einen Speaker von außerhalb, der auch schon einen Raum bei Dräger organisiert hat. Problem: er kann seinen Vortrag nur am 01.11. halten. Wäre bspw. eine Woche später für Dich (und deine Firma) auch in Ordnung?

**Comment by Bongolus** [comment]
@danbim Sorry, aber grundsätzlich nein. Softwerkskammer ist immer am ersten Donnerstag im Monat und ich möchte nicht der sein, der da den Präzedenzfall erschaffen hat. Wir haben ja sowas wie eine Community, wenn da genug damit einverstanden sind, verschiebe ich den gerne, ich will das nur nicht alleine entscheiden.
Welchen Raum wir haben können, kann ich dir nächste Woche sagen, da unser Pförtner anscheinend die Woche Urlaub hat.

**Comment by danbim** [comment]
Valider Punkt das mit der Community. Ich stelle mal einen Poll bei Meetup ein ;-)

**Comment by danbim** [comment]
Hier der Poll: https://www.meetup.com/Softwerkskammer-Luebeck/polls/1270443/

Hast du eine Mail dazu bekommen? Sonst müsste ich den wahrscheinlich separat als Mail an die Gruppenteilnehmer rumschicken...

**Comment by Bongolus** [comment]
@danbim 
Mail habe ich nicht bekommen, nur die Info, dass du hier in den Issue geschrieben hast.

Ich finde die Frage etwas zu allgemein formuliert, es geht ja darum, ob wir meinen Vortrag für den anderen Vortrag verschieben sollen, weil sich genug für beide interessieren. Wenn wir einfach nur das abfragen, hätte das auch den Vorteil, dass wir dann gleich ein Protokoll für's nächste Mal haben (beim nächsten Terminkonflikt halt die alternativen Termine absprechen und dann wieder einen Poll machen)

**Comment by danbim** [comment]
Ist absichtlich so allgemein formuliert weil Terminkonflikte jetzt regelmäßiger auftreten könnten. Daher hätte ich gerne etwas Feedback von den Teilnehmer wie wichtig ihnen das regelmäßige ist. Ich finde es ehrlich gesagt zu aufwändig da jedes Mal zu versuchen das am ersten Donnerstag im Monat zu schaffen. In HH bei den Meetups gibt es solche Regeln selten bis gar nicht, dadurch ist es für Speaker und Organisatoren einfacher...

**Comment by Bongolus** [comment]
Es beantwortet aber auch nicht die im Raum stehende Frage

**Comment by Bongolus** [comment]
@danbim 
Der Raum fasst mit Tischen 25 Leute und ohne Tische 40.

Und hier Version 1 vom Anreißer:

Funktionale Programmierung, das unbekannte Wesen. Man liest alle paar Jahre mal etwas darüber, aber was macht funktionale Programmierung anders und wie sehen Lösungsansätze für Probleme in der funktionalen Programmierung aus?

Ich möchte mit euch einen Rundumschlag zum Thema funktionale Programmierung machen, indem ich euch zuerst Unterschiede zum objektorientierten Paradigma erkläre und euch in einem praktischen Teil die Anwendung der daraus resultierenden Pattern zeige.

Mitzubringen wären:
 - viel Phantasie
 - das grundsätzliche Verständnis einer objektorientierten Programmiersprache

**Comment by thilko** [comment]
@Bongolus ok, habe Termin aktualisiert. Veranstaltungsort kommt noch. Finde ich super! Das ist das Technikzentrum in der City, oder?

**Comment by thilko** [comment]
... hätte jetzt mal mit 25 Leuten angefangen und wenn die Warteliste sehr voll wird, dann können wir noch entscheiden, ob wir enger zusammenrücken.

**Comment by Bongolus** [comment]
@thilko Jup, wir bekommen auch den alten Raum, da sitzen wir schön unter den Augen der Patrizier ;)

**Comment by Bongolus** [comment]
@danbim @thilko 
Wir sind ja leider nicht fertig geworden und ich habe einen Folgetermin angeboten. Dazu bräuchte ich aber einen Raum (und einen Termin). Ich würde das gerne gleich am 15.11. erledigen, kriegen wir da was hin?

LG Bongolus (Ralph)

**Comment by danbim** [comment]
Moin Ralph!

Erstmal vielen vielen Dank für Dein Engagement, finde ich echt super :).

Zum 15.11.: Davon abgesehen dass *ich* an dem Tag nicht kann (d'oh) finde ich den November schon sehr voll. Es stehen noch die MetaNook am 09.11. und der Global Day of Code Retreat am 17.11. an. Wäre es für dich auch eine Option das in einem anderen Monat zu machen?

**Comment by danbim** [comment]
Ich habe übrigens in #16 ein extra ticket dafür aufgemacht.
