### ISSUE TITLE
2018-09-27 - Enterprise Application Integration mit Apache Camel

### ISSUE THREAD

**Issue by basis42** [softwerkskammer-hl/softwerkskammer-hl#11]
Auch wenn im Zeitalter von Microservices die entsprechenden Integrationsaufgaben dank REST glücklicherweise viel von ihrem Schrecken verloren haben, die Integration von Altsystemen und exotischen Schnittstellen mit einem Zoo von Protokollen, Endpunkten und deren Verfügbarkeit bleibt eine alltägliche Herausforderung.

Mit Apache Camel steht für diese Herausforderung ein leichtgewichtiges Enterprise Application Integration Framework zur Verfügung, welches nicht nur über 200 Integrationen out-of-the-box bereitstellt, sondern auch anspruchsvolle Integrationsszenarien mit wenig Aufwand realisierbar macht.

Überzeugt euch selbst anhand von Beispielen aus dem eCommerce-Umfeld, wie viel Spaß EAI machen kann und schaut, ob wir gemeinsam das Kamel zum laufen bringen!

Ziel des Vortrags ist es, den Zuhörern zum einen die theoretischen Grundlagen von Enterprise Application Integration nahe zu bringen. Weiterhin soll anhand einer Casestudy demonstriert werden,  dass Apache Camel auch bei komplexen Integrationsaufgaben nicht langjähriges Expertenwissen voraussetzt.

**Comment by basis42** [comment]
Also, für den Fall, das es da Interesse gibt: Ich könnte da was zu sagen 😉 🐫 .

**Comment by danbim** [comment]
Sehr cooler Vorschlag Mario! Ich wäre jedenfalls sehr interessiert :)

**Comment by basis42** [comment]
Ach und als Termin würde mit 10/2018 gut passen, falls da noch nichts ist. Ansonsten natürlich auch gern später.

**Comment by danbim** [comment]
Perfekt! Da hatten wir bisher noch nichts geplant. 10/2018 ist deiner ;-).

(wenn es aus irgend einem Grund doch nicht klappt wäre es super wenn Du frühzeitig Bescheid sagst so dass jemand anderes nachrutschen kann)

**Comment by danbim** [comment]
Moin @basis42 ! Da am Mittwoch, den 03.10. Feiertag ist und sicher einige Leute ein langes Wochenende nehmen, würde ich es fast besser finden das Meetup in die Woche davor oder danach zu verlegen. (Meine Tendenz wäre danach, dann kann ich auch da sein ;-)). Könntest Du also auch am 27.09. bzw. 11.10.?

@thilko Was denkst Du? Abweichen von der Regel "erster Donnerstag im Monat" OK?

**Comment by basis42** [comment]
Der 27.09. würde mir passen, 11.10. bin ich schon verplant.

**Comment by basis42** [comment]
@thilko, Wie siehts mit der Terminplanung? Ich gehe mit @danbim das der 4. vielleicht nicht so gut ist, andererseits ist vorziehen wohl auch nicht so toll, oder?

**Comment by TobiasMende** [comment]
Sehr cool! Da freue ich mich drauf. Mit Camel haben wir auch gerade zu tun 🐫 und mit Glück bin ich da sogar in HL 😃  (ich bin für den 27.09. oder 04.10.)

**Comment by thilko** [comment]
@danbim @basis42 Persönlich mag ich lieber die Regelmäßigkeit und würde den 04.10. präferieren. Finde es aber auch OK wenn wir den Termin um 1 Woche verschieben. Mit dem 27.09. hätten wir dann 3 Termine in einem Monat ;-) 

Thema finde ich richtig super!

**Comment by thilko** [comment]
@danbim @basis42 ok, habe festgestellt das ich am 04/10 in der Tat im Urlaub bin :-D 

dann lass uns das doch am 27.09. machen. Ich bereite die Meetup Termine vor. 

Passt das für Euch?

**Comment by danbim** [comment]
Bin da leider auch im Urlaub 😩

**Comment by thilko** [comment]
@danbim dann lass uns nochmal kurz sprechen. Am 27.09. steht auch das Chaotikum nicht zu Verfügung. @basis42 04/10 und 27/09 sind immmer noch beide für Dich ok, oder?

**Comment by danbim** [comment]
Wäre ein Tausch der Talks mit @Bongolus eine Option? Also F# am 11.10. und Camel im November? Was sagt Ihr @Bongolus und @basis42?

**Comment by basis42** [comment]
4.10. und 27.9. sind für mich beide ok, tauschen würde ich ungern, der November ist bei mir recht voll.

**Comment by danbim** [comment]
Ich bin weder am 27.09. noch am 04.10. da weil Urlaub. @thilko Du bist ja am 27.09. da also kannst Du das ja machen ;-). Dann bin ich eben nicht dabei... Bräuchten wir nur einen anderen Raum.

**Comment by danbim** [comment]
Alles geplant, schließe das Issue. Danke für dein Engagement Mario!

**Comment by basis42** [comment]
@danbim Ich merke mal an, das uns noch eine Örtlichkeit fehlt ...

**Comment by danbim** [comment]
Oh, danke für den Hinweis! @thilko hast Du was an der Hand für den 27.? Ich bin ja wie gesagt nicht da. Bei mir wird's auch diese Woche etwas knapp mich um einen Raum zu kümmern denn ich fahre Freitag in Urlaub.

**Comment by thilko** [comment]
@danbim ich wollte mal beom Cloudsters nachfragen

**Comment by thilko** [comment]
@danbim @basis42 Cloudsters als Location steht. Was war das Limit beim letzten Mal? 25?

**Comment by danbim** [comment]
25 hatte ich eingetragen, 20 kamen und passten rein. Können wir ja ruhig wieder so machen.

**Comment by thilko** [comment]
@basis42 hast du für Donnerstag besonderen Bedarf wegen des Beamers? Frage sonst nochmal beim Cloudsters aus wie das aussieht

**Comment by basis42** [comment]
@thilko @danbim : Es tut mir super leid, aber ich muss den Talk am Donnerstag aus gesundheitlichen Gründen absagen. Ich hab mir die Entscheidung nicht leicht gemacht, ihr hab das so super organisiert und ich bin auch schon wieder deutlich auf dem Weg der Besserung, aber es ist einfach noch zu früh. 

Ich würde den 4.10.(Do. nächste Woche) anbieten oder aber, da das ja recht kurzfristig ist, natürlich auch gern später.

**Comment by thilko** [comment]
Oje, gute Besserung! Ich kläre das mal mit den anderen Organisatoren.

**Comment by thilko** [comment]
OK, dann machen wir den 04.10. draus. Passt das?

**Comment by thilko** [comment]
Ich lege dass dann mal auf den 04.10.!

**Comment by basis42** [comment]
@thiko für mich ist 4.10. super. Bleibt es beim Cloudsters in der Dankwartsgrube? Außer einem Beamer wäre wlan klasse, aber falls da nichts ist, mach ich mir selbst einen AP auf.

**Comment by thilko** [comment]
@basis42 Nein, das Treffen würde dann im Chaotikum sein. Ist dann auch die Premiere an der  neuen Location :-)

**Comment by basis42** [comment]
Sehr schön, ich freue mich :-)!

**Comment by thilko** [comment]
Das hat Spaß gemacht! Gerne wieder :-)
