### ISSUE TITLE
Gamification mal ausprobiert

### ISSUE THREAD

**Issue by thilko** [softwerkskammer-hl/softwerkskammer-hl#12]

**Comment by thilko** [comment]
@danbim findet am 01.11. statt. Beschreibung folgt.

**Comment by danbim** [comment]
@thilko Am 01.11. haben wir schon den F#-Talk!

**Comment by thilko** [comment]
oh mist... das habe ich nicht gesehen...

**Comment by danbim** [comment]
Verschoben nach https://github.com/agile-lean-hl/agile-lean-hl/issues/1.
