### ISSUE TITLE
2019-01-03 Back to the roots - Refactoring Coding Dojo

### ISSUE THREAD

**Issue by mariodavid** [softwerkskammer-hl/softwerkskammer-hl#13]
Hi everyone, 

I had the idea to do a coding dojo for refactoring. On the occasion of the 20th anniversary of the [original refactoring book](http://a.co/d/0DsqpAE) and the release of the [second edition](http://a.co/d/idfjVwN) I decided to re-read the original book recently after a couple of years and I unfortunately could not really remember most of the stuff (which tells you more about my ability to absorb knowledge then about the content of the book). 

The only thing left in my mind was a fluffy idea of the term. So I thought in order to make myself aware of the details & concrete steps - a coding dojo might be a good opportunity for me (and hopefully for others as well).

If there is enough interest, I would like to do that and share & learn with you in a form this coding dojo.

The description is something along those lines:

---------------------------------------

## Back to the roots - refactoring coding dojo

Refactoring is a term that most developers and IT related people are aware of. However it seems for most people it is more a fluffy concept that means a lot of things to a lot of people. It can go from "renaming a variable" to "let's rewrite our monolithic application to microservices in a multi year process" or "I add some functionality to my application". 

But did you know that refactoring does also (if not exclusively) mean something very concrete like `Consolidate Duplicate Conditional Fragements` or `Introduce Parameter Object` executed in a clearly defined & safe way? And that it is a [noun as well as a verb](https://martinfowler.com/bliki/DefinitionOfRefactoring.html) with slightly different meanings?

During this coding dojo we want to get back to the roots and with that away from the fluffy - everyone understands & no one understands - idea of refactoring. As for any good coding dojo, we will make it concrete through actual coding.

We will refactor *real* pieces of code in small groups via safe steps, compare the code *before* and *after* and finally exchange our opinions about benefits & tradeoffs.

After the dojo, everyone should have a refreshed understanding of the origins of refactorings. It should be clear what types of refactoring techniques are around and what the process for executing concrete refactorings looks like. As a side effect everyone will learn a little bit about clean code as this ideas are very related.

---------------------------------------

Please let me know what you think & if there is anything that is missing or if there is something that you would like to see differently.

Bye
Mario

**Comment by danbim** [comment]
Moin Mario! Klingt großartig, endlich mal wieder ein Coding-Event ;-). Wir haben jetzt bereits die Meetups für September, Oktober und November eingeplant, du müsstest Dich also mit @thilko (#12) um den Dezember kloppen oder im Januar den Coding Dojo machen.
Alternativ können wir auch mehrere Events im Monat starten, allerdings mit der Gefahr dass es etwas viel wird und uns im Worst Case im neuen Jahr die Themen ausgehen.

**Comment by mariodavid** [comment]
Moin,

Jo, hört sich gut an. Zeitkritisch ist das nicht. Dann hab ich zumindest genug zeit die beispiele vorzubereiten. Kann also ruhig dez / jan werden...

Bis dann
Mario

**Comment by LueBecko** [comment]
Moin,

die MACH AG könnte für diesen Anlass einen Besprechungsraum stellen.

Was meint ihr dazu?

LG Christian

ps: wir diskutieren auch intern viel über richtiges Refactoring und machen es oft dann doch nicht richtig. Daher besonders spannedn für uns :)

**Comment by danbim** [comment]
Moin Christian! Das klingt großartig, danke! @mariodavid Wäre Januar eine Option für dich? Grüße

**Comment by mariodavid** [comment]
moin,

jo das sollte passen: 3.1., korrekt?.

Bis dann
Mario

**Comment by danbim** [comment]
Ja, 03.01. ist jetzt gesetzt :). Stellt Ihr bei Element den Raum @mariodavid ?

**Comment by mariodavid** [comment]
Ähh, ja könnten wir wohl hinbekommen. Aber wieso - passt dir die MACH AG als Location nicht? ;)

**Comment by danbim** [comment]
Äh nein, die passt mir gut :D. Hatte nur das "Needs Location"-Label noch gesehen und wohl ein bisschen den Überblick verloren.

**Comment by LueBecko** [comment]
moin, was haltet ihr davon die Location noch zu verschieben? Wir von MACH haben jetzt einen zweiten Standort in Lübeck und der ist richtig schick. MFC X Maria Goepert Straße 16.

Und vielleicht sollte man in die Announcements noch reinschreiben, das BOYD gilt?

**Comment by danbim** [comment]
Finde ich gut! @mariodavid up to you :)

**Comment by mariodavid** [comment]
jo, können wir gerne machen. Haben wir da ein paar Tische? Das wäre cool, wenn die Leute auch wirklich "hands on" was machen sollen :=)

**Comment by LueBecko** [comment]
Tische haben wir ;) Und auch Platz um in einen weiteren Besprechungsbreich auszuweichen, wenn es eng wird.

Wir haben aber kein Gäste WLAN. Also wenn du plannst irgendwelche Datein zu verteilen müssen wir uns da einen anderen Weg einfallen lassen.

**Comment by LueBecko** [comment]
Kann jemand die Ankündigung auf Meetup bitte aktualisieren? Wer macht das normalerweise? @thilko ? @danbim ?

**Comment by mariodavid** [comment]
Ok, das passt schon auch ohne WLAN. Ich schreib noch ne Mail rum, damit die Leute sich ggf. die Reops herunterladen können und dann klappt das bestimmt auch so!

Gruß
Mario

**Comment by thilko** [comment]
@LueBecko @mariodavid Veranstaltungsort ist angepasst und BYO steht auch im Text, schicke dann beizeiten die Einladung raus. Gibt es ein Teilnehmerlimit?

**Comment by mariodavid** [comment]
hmm. Ich denke mit mehr als 20 Leuten macht es nicht mehr so viel sinn, zumindest wenn man die Ergebnisse der anderen in der Gruppe besprechen will. Wenn es wirklich mehr sein sollten, könnte man noch darüber nachdenken das wegzulassen oder so. Aber ich würde erstmal sagen 20 Leute. Wie viel Platz ist denn bei euch @LueBecko ?

**Comment by LueBecko** [comment]
Ich dachte, dass wir immer zusammen starten in einem größeren Raum und für die Dojo-Bearbeitung dann in benachbarte kleinere Besprechungsecken auswandern um danach dann wieder im ersten Raum zusammenzukommen. 20 könnte auch schon sehr kuschelig werden - ich hab eher mit 15 gerechnet. Aber sollten es mehr werden kriegen wir das auch hin.

Brauchst du einen Beamer, oder sowas?

**Comment by mariodavid** [comment]
Ich glaub Thilko hat ne Grenze von 20 Leuten bei Meetup eingestellt - mehr sollten es also nicht werden.

Jo, das mit den mehreren Räumen hört sich ganz gut an. Ein Beamer wäre ganz gut, ja :) - Ich hab HDMI, passt das?
