### ISSUE TITLE
2018-12-06 Hansehack Nachbereitung

### ISSUE THREAD

**Issue by LueBecko** [softwerkskammer-hl/softwerkskammer-hl#14]
Werden Ideen vom Hansehack weiterverfolgt? Wer hat Lust mehr daraus zu machen? Wer würde sich gerne einbringen bei solchen Unternehmungen?

Es geht darum den Impuls vom Hansehack zu manifestieren, in Form von Initiativen, Bastelgruppen, Produkten, vielleicht Gründungen, ...

Dabei stehen an dieser Stelle wieder Ideen (es müssen nicht unbedingt die selben sein wie vom Hansehack) und die Möglichkeit sich in (bestehende oder möglicherweise neu formende) Teams einzubringen. Und vielleicht kommt so dann doch eine kritische Masse zusammen um mehr daraus zu machen.

Es soll eine offene Diskussion geben wo jeder seine Ideen und Fantasien vorstellen darf.
Zusätzlich würden wir uns um einen Ansprechpartner vom Gründercube bemühen für entsprechende offene Fragen.

Die Softwerkskammer als gut etablierte Community biete sich als Organisationsrahmen dafür an. Ein zeitnaher Termin wäre praktisch, damit die "Euphorie" nicht verpufft.

Was sagt ihr dazu?

**Comment by danbim** [comment]
Moin @LueBecko ! Ist für den 06.12. eingeplant :) https://www.meetup.com/Softwerkskammer-Luebeck/events/gjsxslyxpbcb/
