### ISSUE TITLE
LoRaWAN - was ist das eigentlich?

### ISSUE THREAD

**Issue by thilko** [softwerkskammer-hl/softwerkskammer-hl#15]
Ich möchte einen praktischen Einstieg in LoRaWAN geben. Grober Inhalt:

* LoRaWAN Einführung
* LoRaWAN Infrastruktur
* Vorteile und Einsatzsuenarien

... danach kann möglichst jeder Teilnehmer mit der gegebenen Hardware rumspielen.

**Comment by danbim** [comment]
@thilko wird das am 06.12. (https://www.meetup.com/Softwerkskammer-Luebeck/events/gjsxslyxpbcb/ bzw. #14 ) mit behandelt?

**Comment by thilko** [comment]
UNter Umständen - Idee ist, das wir eher ein offenes Moderationsformat machen, da das eigentliche Thema der Hackathon ist. Also vermutlich eher weniger - ist aber auch nicht schlimm für mich

**Comment by thilko** [comment]
closed because of inactivity
