### ISSUE TITLE
Funktionale Pattern in F#

### ISSUE THREAD

**Issue by danbim** [softwerkskammer-hl/softwerkskammer-hl#16]
Follow up zu #10

**Comment by Bongolus** [comment]
Hey!

Der Termin ist mir eigentlich egal, muss auch nicht unbedingt an einem Donnerstag sein. Mir wäre halt nur "so schnell wie möglich" ganz lieb. Einerseits sind die Erinnerungen noch frisch und ich möchte das Thema auch mal zu Ende bringen :)

LG Ralph

**Comment by Bongolus** [comment]
@danbim @thilko 
Moin!

Ich habe mal meine Termine im Dezember gecheckt. Ich bin am 14. den ganzen Tag unterwegs, weswegen ich das auch ungerne am 13. machen würde. Ansonsten hab ich Zeit.

Müsste doch möglich sein mit solchen Vorgaben einen Termin zu finden ;p

Greetz Ralph

**Comment by thilko** [comment]
@Bongolus Ich sehe das so: der regelmäßige Takt von 1. Donnerstag im Monat soll den organisatorischen Aufwand gering halten und sich die Softwerkskammer möglichst selbst organisieren lassen. 

Vorteile: 
* wir haben fest für den 1. Do im Monat das Chaotikum gebucht und müssen uns keine Gedanken um eine Location machen
* Planungssicherheit für die Community

Ich kann verstehen wenn Du das schneller vorstellen willst(ich finde es auch gut) - der nächste freie Termin wäre auch erst Anfang März. Und da wir eher als selbstorganisiertes Netzwerk agieren mein Vorschlag:

1. Suche einen Termin der für Dich passt und nicht zu dicht an den regulären Terminen liegt
2. Organisiere eine Location (Chaotikum, oder bei Euch im Technikzentrum etc.)
3. Wir stellen einen zusätzliches Meetup bei der Softwerkskammer ein

Damit haben wie Organisationsaufwände etwas besser verteilt und die Flexibilität mehr Themen zu besrechen.

Was meinst du?

**Comment by Bongolus** [comment]
"Ich kann verstehen wenn Du das schneller vorstellen willst"

Das mit dem "verstehen" ist halt so ne Sache, ich will es nicht schneller vorstellen, ich will mein Referat/Vortrag vom November beenden und hatte dazu an dem Abend angeboten, es außer der Reihe zu machen, wenn wir einen Raum bekommen, damit die nicht 4-5 Monate auf den Followup warten müssen.

Also meine ehrliche Meinung wäre, du liest erstmal bevor du schreibst.

**Comment by thilko** [comment]
"Mir wäre halt nur "so schnell wie möglich" ganz lieb."
Was bedeutet, einen Termin außerhalb der Reihe zu organisieren. Wann möchtest Du denn den Vortrag halten?

**Comment by Bongolus** [comment]
Ja, es geht darum einen Termin, mit Raum, außer der Reihe zu organisieren, um den Vortrag zu **beenden** (das mit dem Beenden ist mir wichtig, sonst würde ich mich ja vordrängeln ;)

Ich habe mit Absicht auch keine konkreten Termine genannt, weil ich einerseits nicht "die Pistole auf die Brust" setzen wollte, die Frage war ja auch lediglich, ob wir da was organisiert bekommen und andererseits wurde mein letzter Terminvorschlag ohne Gegenvorschlag abgebügelt, also werde ich den Fehler auch kein zweites Mal machen.

P.S. Das letzte was ihr wollt ist, dass die Leute in einem "selbstorganisiertes Netzwerk" selber anfangen hier nach Räumen zu suchen. Sowas muss zentral organisiert werden, sonst wird es alsbald Beschwerden geben, weil ständig Leute anrufen und nach Räumen fragen.

**Comment by Bongolus** [comment]
@danbim @thilko 

Name: Grundlagen F#/Funktionale Pattern Fortsetzung
Teaser: 
Followup zu:
https://www.meetup.com/de-DE/Softwerkskammer-Luebeck/events/254680896/

Like cleaning a house, it never stops!

Termin: 18.12.18 19:00 Chaotikum

Bitte fix einstellen, sind ja nur noch 2 Wochen ...

**Comment by danbim** [comment]
Moin Ralph!

Hab den Termin soeben eingestellt. Ich würde gerne mit dir kurz über die aufgekommenen Missverständnisse reden hier im Thread. Wenn du das auch möchtest könntest du mir deine Telefonnummer an daniel@bimschas.com senden, dann rufe ich dich an.

Gruß 
Daniel

**Comment by Bongolus** [comment]
Du hast es geschafft, dass die Einladung für den 6.12. raus ging ...
Ich möchte das Ganze nur noch zu Ende bringen und unter Erfahrung verbuchen.

**Comment by danbim** [comment]
Wenige Sekunden später hatte ich den Termin bereits korrigiert. Was möchtest du denn jetzt von mir? Wünschst du dir dass ich noch mal eine Mail rum schicke?

**Comment by thilko** [comment]
@danbim danke für´s einstellen!
