### ISSUE TITLE
Remote Speaker: David Völkl

### ISSUE THREAD

**Issue by thilko** [softwerkskammer-hl/softwerkskammer-hl#20]
Habe David Völkl gefragt, ob er einen Vortag bei der SWK machen möchte. Passt bei Ihm gut und wir suchen jetzt noch nach einem geeigneten Termin.

Vortag selbst wird remote sein.

Termin: 10.Oktober

**Comment by thilko** [comment]
http://www.davidvoelkel.de/

**Comment by danbim** [comment]
@thilko Ist das noch aktuell hier oder kann das weg?

**Comment by thilko** [comment]
weg ;-)
