### ISSUE TITLE
Emotional Programming

### ISSUE THREAD

**Issue by mattelacchiato** [softwerkskammer-hl/softwerkskammer-hl#21]
Ahoi!

@danbim bat mich, meinen Vortrag zu "Emotional Programming" bei euch einzureichen.

Abstract:
Endless team discussions and crazy argues may happen in every team. But those situations are not destiny. We don’t have to be captivated in our emotions. See how we are able to adjust our inner automated processes in challenging situations. We can shape a mindful team culture and increase efficiency.

Bio:
During his computer science study, Matthias got hooked on software craftsmanship. He is convinced that easily readable code and test driven development will result in sustainable software. At inoio he plans, builds and maintains software projects like fraud prevention solutions, event sourced media distribution or data processing for sustainable agriculture.
Typically, software projects don’t struggle because of technology, but because of errors in human interaction. Therefore Matthias also works on shaping team culture by enhancing communication and mindfulness skills.

Schöne Grüße aus Hamburg,
Matthias

**Comment by danbim** [comment]
@thilko Ich bin noch nen Monat in Elternzeit, vielleicht magst Du da schon mit Matthias was planen? :) LG

**Comment by danbim** [comment]
Und natürlich großartig von Dir @mattelacchiato dass Du uns in Lübeck mit Deinem (sehr guten ;-)) Vortrag beehren willst :)

**Comment by danbim** [comment]
@mattelacchiato Event ist angekündigt! https://www.meetup.com/Softwerkskammer-Luebeck/events/gjsxslybchbkb/

**Comment by danbim** [comment]
Und auf https://www.softwerkskammer.org/activities/emotional-programming
